development:
  database: coesapp_development
  adapter: mysql2
  encoding: utf8
  pool: 5
  username: root
  password: d15573230
  socket: /tmp/mysql.sock

production:
  adapter: mysql2
  url: <%= ENV['DATABASE_URL'] %>
  encoding: utf8
  pool: 5